<a href="https://colab.research.google.com/github/mnwanaGit/PS2HouseDataExercise/blob/master/MN_HousePriceRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import pandas as pd #import statements
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [37]:
train = pd.read_csv('/train.csv') #loading in data
test = pd.read_csv('/test.csv')

In [38]:
corrs = abs(train.corr()) #correlation logic: choose the variables with the 10 highest absolute value of correlation coefficient
print(corrs)

                     Id  MSSubClass  LotFrontage  ...    MoSold    YrSold  SalePrice
Id             1.000000    0.011156     0.010601  ...  0.021172  0.000712   0.021917
MSSubClass     0.011156    1.000000     0.386347  ...  0.013585  0.021407   0.084284
LotFrontage    0.010601    0.386347     1.000000  ...  0.011200  0.007450   0.351799
LotArea        0.033226    0.139781     0.426095  ...  0.001205  0.014261   0.263843
OverallQual    0.028365    0.032628     0.251646  ...  0.070815  0.027347   0.790982
OverallCond    0.012609    0.059316     0.059213  ...  0.003511  0.043950   0.077856
YearBuilt      0.012713    0.027850     0.123349  ...  0.012398  0.013618   0.522897
YearRemodAdd   0.021998    0.040581     0.088866  ...  0.021490  0.035743   0.507101
MasVnrArea     0.050298    0.022936     0.193458  ...  0.005965  0.008201   0.477493
BsmtFinSF1     0.005024    0.069836     0.233633  ...  0.015727  0.014359   0.386420
BsmtFinSF2     0.005968    0.065649     0.049900  ...  0.015211  0.031706   0.011378
BsmtUnfSF      0.007940    0.140759     0.132644  ...  0.034888  0.041258   0.214479
TotalBsmtSF    0.015415    0.238518     0.392075  ...  0.013196  0.014969   0.613581
1stFlrSF       0.010496    0.251758     0.457181  ...  0.031372  0.013604   0.605852
2ndFlrSF       0.005590    0.307886     0.080177  ...  0.035164  0.028700   0.319334
LowQualFinSF   0.044230    0.046474     0.038469  ...  0.022174  0.028921   0.025606
GrLivArea      0.008273    0.074853     0.402797  ...  0.050240  0.036526   0.708624
BsmtFullBath   0.002289    0.003491     0.100949  ...  0.025361  0.067049   0.227122
BsmtHalfBath   0.020155    0.002333     0.007234  ...  0.032873  0.046524   0.016844
FullBath       0.005587    0.131608     0.198769  ...  0.055872  0.019669   0.560664
HalfBath       0.006784    0.177354     0.053532  ...  0.009050  0.010269   0.284108
BedroomAbvGr   0.037719    0.023438     0.263170  ...  0.046544  0.036014   0.168213
KitchenAbvGr   0.002951    0.281721     0.006069  ...  0.026589  0.031687   0.135907
TotRmsAbvGrd   0.027239    0.040380     0.352096  ...  0.036907  0.034516   0.533723
Fireplaces     0.019772    0.045569     0.266639  ...  0.046357  0.024096   0.466929
GarageYrBlt    0.000072    0.085072     0.070250  ...  0.005337  0.001014   0.486362
GarageCars     0.016570    0.040110     0.285691  ...  0.040522  0.039117   0.640409
GarageArea     0.017634    0.098672     0.344997  ...  0.027974  0.027378   0.623431
WoodDeckSF     0.029643    0.012579     0.088521  ...  0.021011  0.022270   0.324413
OpenPorchSF    0.000477    0.006100     0.151972  ...  0.071255  0.057619   0.315856
EnclosedPorch  0.002889    0.012037     0.010700  ...  0.028887  0.009916   0.128578
3SsnPorch      0.046635    0.043825     0.070029  ...  0.029474  0.018645   0.044584
ScreenPorch    0.001330    0.026030     0.041383  ...  0.023217  0.010694   0.111447
PoolArea       0.057044    0.008283     0.206167  ...  0.033737  0.059689   0.092404
MiscVal        0.006242    0.007683     0.003368  ...  0.006495  0.004906   0.021190
MoSold         0.021172    0.013585     0.011200  ...  1.000000  0.145721   0.046432
YrSold         0.000712    0.021407     0.007450  ...  0.145721  1.000000   0.028923
SalePrice      0.021917    0.084284     0.351799  ...  0.046432  0.028923   1.000000

[38 rows x 38 columns]

From correlation sheet, top 10 variables with highest absolute value of correlation coefficient:

    1. OverallQual
    2. GrLivArea
    3. GarageCars
    4. GarageArea
    5. TotalBsmtSF
    6. 1stFlrSF
    7. FullBath
    8. TotRmsAbvGrd
    9. YearBuilt
    10. YearRemodAdd

In [39]:
x = train[['OverallQual', 'GrLivArea', 'GarageCars', 'GarageArea',
                           'TotalBsmtSF', '1stFlrSF', 'FullBath', 'TotRmsAbvGrd',
                           'YearBuilt', 'YearRemodAdd']]

y = train['SalePrice']

x_train, x_valid, y_train, y_valid = train_test_split(x, y, test_size=0.33, random_state=42) #creating our training/validation data

In [40]:
reg = LinearRegression().fit(x_train, y_train) #fitting the linear regression model

In [41]:
print("Training R^2 is:", reg.score(x_valid, y_valid))

Training R^2 is: 0.789103005300775

In [42]:
y_pred = reg.predict(x_train) #getting prediction (Example)

y_pred[0]

153563.13157781702

In [43]:
test_predictors = test[['OverallQual', 'GrLivArea', 'GarageCars', 'GarageArea',
                           'TotalBsmtSF', '1stFlrSF', 'FullBath', 'TotRmsAbvGrd',
                           'YearBuilt', 'YearRemodAdd']] #pulling back the predictors we used to train the model

pred_prices = reg.predict(test_predictors) #predicting the true test data's sale prices
test['SalePrice(pred)'] = pred_prices

test.head()

     Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice(pred)
0  1001          20       RL  ...        WD         Normal    67591.005473
1  1002          30       RL  ...        WD        Abnorml    73529.307126
2  1003          20       RL  ...        WD         Normal   268492.852553
3  1004          90       RL  ...        WD         Normal   182526.502117
4  1005         120       RL  ...        WD         Normal   223977.416240

[5 rows x 81 columns]

In [44]:
ship_out = pd.DataFrame() #creating a dataframe with only ID's and predicted saleprices to ship out

ship_out['Id'] = test['Id']
ship_out['SalePrice(pred)'] = test['SalePrice(pred)']
ship_out.head()

     Id  SalePrice(pred)
0  1001     67591.005473
1  1002     73529.307126
2  1003    268492.852553
3  1004    182526.502117
4  1005    223977.416240

In [48]:
ship_out.to_csv('/predictions.csv')